[package]
name = "esc-driver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
device-driver = "0.5"
bitvec = "1.0"
num_enum = "0.7"
defmt = "0.3"
